language: python

python:
  - "3.6"

install:
  # Display the Python version we are running now
  - python --version
s
  # Install additional requirements (Keras and Tensorflow CPU-Version)
  - pip install -r ModelTrainer/requirements.txt
  
  # List installed packages for debuggin purposes
  - pip list

script:
  - pytest --cov=./ ModelTrainer/ -s

after_success:
  - codecov